name: Build Atmosphere

on:
  push:
    branches:
      - evaron-master
    paths-ignore:
      - 'Dockerfile'
      - '.github/workflows/image.yml'

jobs:
  build-workflow:
    uses: ./.github/workflows/build-jobs.yaml
